package grupo1.client5605.iu.painel;

public class tet {
	/*
	 * To change this template, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/*
	 * Principal.java
	 *
	 * Created on 25/02/2010, 20:56:34
	 */
	package twitterclienteparte2;

	import java.awt.Color;
	import java.awt.FlowLayout;
	import java.awt.Image;
	import java.awt.event.KeyEvent;
	import javax.swing.ImageIcon;
	import javax.swing.JLabel;
	import javax.swing.JOptionPane;
	import javax.swing.JPanel;
	import javax.swing.JTextArea;
	import javax.swing.border.LineBorder;
	import twitter4j.Status;
	import twitter4j.Twitter;
	import twitter4j.TwitterException;
	import twitter4j.User;

	/**
	 *
	 * @author Felipe
	 */
	public class Principal extends javax.swing.JFrame {
	    private Twitter t;
	    private User eu;
	    Image foto;

	    /** Creates new form Principal */
	    public Principal(Twitter t, User eu) {
	        this.t = t;
	        this.eu = eu;
	        initComponents();
	        recuperarDados();        
	    }

	    private void recuperarDados() {
	        this.foto = this.getToolkit().getImage(eu.getProfileImageURL());
	        jL_Foto.setIcon(new ImageIcon(foto));
	        String ultimo = eu.getStatus().getText();
	        if (ultimo.length() > 50) {
	            ultimo = ultimo.substring(0, 50) + "...";
	        }
	        jL_Ultimo.setText(ultimo);

	        carregaTimeline();
	    }

	    public void carregaTimeline() {
	        try {
	            JPanel pane;
	            JLabel novaFoto;
	            JTextArea msg;
	            int i = 0;

	            jP_Tweets.removeAll();

	            for (Status s : t.getFriendsTimeline()) {
	                i++;
	                //cria o panel
	                pane = new JPanel(new FlowLayout(FlowLayout.LEFT));
	                pane.setBorder(new LineBorder(Color.black, 1));
	                pane.setSize(370, 50);

	                //cria o label com a foto
	                novaFoto = new JLabel(new ImageIcon(this.getToolkit().getImage(s.getUser().getProfileImageURL())));

	                //cria o textarea com o texto
	                msg = new JTextArea(3, 27);
	                msg.setEditable(false);
	                msg.setText(s.getText());
	                msg.setLineWrap(true);

	                pane.add(novaFoto);
	                pane.add(msg);
	                jP_Tweets.add(pane);
	            }

	            jL_Novos.setText(i + " tweets carregados");

	        } catch (TwitterException ex) {
	            JOptionPane.showMessageDialog(this, "Erro recuperando a timeline: " + ex.getMessage());
	        }
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jL_Foto = new javax.swing.JLabel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTA_Status = new javax.swing.JTextArea();
	        jL_Ultimo = new javax.swing.JLabel();
	        jL_Restantes = new javax.swing.JLabel();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        jP_Tweets = new javax.swing.JPanel();
	        jL_Novos = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setTitle("Cliente de Twitter Java Simples");

	        jL_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
	        jL_Foto.setName("jL_Foto"); // NOI18N

	        jScrollPane1.setName("jScrollPane1"); // NOI18N

	        jTA_Status.setColumns(20);
	        jTA_Status.setLineWrap(true);
	        jTA_Status.setRows(2);
	        jTA_Status.setName("jTA_Status"); // NOI18N
	        jTA_Status.addCaretListener(new javax.swing.event.CaretListener() {
	            public void caretUpdate(javax.swing.event.CaretEvent evt) {
	                jTA_StatusCaretUpdate(evt);
	            }
	        });
	        jTA_Status.addKeyListener(new java.awt.event.KeyAdapter() {
	            public void keyTyped(java.awt.event.KeyEvent evt) {
	                jTA_StatusKeyTyped(evt);
	            }
	        });
	        jScrollPane1.setViewportView(jTA_Status);

	        jL_Ultimo.setName("jL_Ultimo"); // NOI18N

	        jL_Restantes.setText("140");
	        jL_Restantes.setName("jL_Restantes"); // NOI18N

	        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ultimos Tweets"));
	        jScrollPane2.setName("jScrollPane2"); // NOI18N

	        jP_Tweets.setName("jP_Tweets"); // NOI18N
	        jP_Tweets.setLayout(new javax.swing.BoxLayout(jP_Tweets, javax.swing.BoxLayout.Y_AXIS));
	        jScrollPane2.setViewportView(jP_Tweets);

	        jL_Novos.setName("jL_Novos"); // NOI18N

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jL_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(10, 10, 10)
	                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jL_Ultimo, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
	                        .addGap(46, 46, 46)
	                        .addComponent(jL_Restantes))
	                    .addComponent(jL_Novos))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
	                    .addComponent(jL_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jL_Ultimo)
	                    .addComponent(jL_Restantes))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jL_Novos)
	                .addContainerGap(25, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void jTA_StatusCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTA_StatusCaretUpdate
	        jL_Restantes.setText(String.valueOf(140 - jTA_Status.getText().length()));
	    }//GEN-LAST:event_jTA_StatusCaretUpdate

	    private void jTA_StatusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTA_StatusKeyTyped
	        if (jTA_Status.getText().length() == 140) {
	            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
	        }

	        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
	            try {
	                t.updateStatus(jTA_Status.getText());
	                jTA_Status.setText("");
	                carregaTimeline();
	            } catch (TwitterException ex) {
	                JOptionPane.showMessageDialog(this, "Erro atualizando o status: " + ex.getMessage());
	            }
	        }
	    }//GEN-LAST:event_jTA_StatusKeyTyped
	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JLabel jL_Foto;
	    private javax.swing.JLabel jL_Novos;
	    private javax.swing.JLabel jL_Restantes;
	    private javax.swing.JLabel jL_Ultimo;
	    private javax.swing.JPanel jP_Tweets;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JTextArea jTA_Status;
	    // End of variables declaration//GEN-END:variables
	}


}
